kind: ConfigMap
apiVersion: v1
metadata:
  name: kfp-model-server
data:
  judge_model_endpoint: "https://mistral-7b-instruct-v02-sallyom.apps.ocp-beta-test.nerc.mghpcc.org/v1"
  judge_model_name: "mistral-7b-instruct-v02"
---
apiVersion: v1
kind: Secret
metadata:
  name: kfp-model-server
type: Opaque
stringData:
  judge_api_key: ""
