apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: <NAMESPACE>
  name: singlenode-training
spec:
  selector:
    matchLabels:
      app: singlenode-training
  replicas: 1
  template:
    metadata:
      labels:
        app: singlenode-training
    spec:
      containers:
        - name: container
          image: quay.io/shanand/test-train:0.0.4
          resources:
            limits:
              nvidia.com/gpu: '2'
            requests:
              nvidia.com/gpu: '2'
          command:
            - /bin/bash
            - '-c'
            - '--'
          args:
            - python3.11 -m run.py
            - while true; do sleep 300; done
